src/Entity/Sortie.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\SortieRepository;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=SortieRepository::class)
 * @UniqueEntity(fields={"coup"},message="Ce numéro existe déjà")
 */
class Sortie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     * @Assert\NotBlank(message="Le numéro est obligatoire")
     * @Assert\Length(max=20,maxMessage="La caractère du numéro est au maximum 20 caractères")
     */
    private $coup;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotBlank(message="La date de sortie est obligatoire")
     * @Assert\Date
     * @var string A "Y-m-d" formatted value
     */
    private $date_sortie;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Le montant est obligatoire")
     * @Assert\PositiveOrZero(message="Le montant est au minimum 0")
     */
    private $coup_sortie;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Le motif est obligatoire")
     */
    private $cause;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCoup(): ?string
    {
        return $this->coup;
    }

    public function setCoup(string $coup): self
    {
        $this->coup = $coup;

        return $this;
    }

    public function getDateSortie()
    {
        return $this->date_sortie;
    }

    public function setDateSortie($date_sortie): self
    {
        $this->date_sortie = $date_sortie;

        return $this;
    }

    public function getCoupSortie(): ?int
    {
        return $this->coup_sortie;
    }

    public function setCoupSortie(int $coup_sortie): self
    {
        $this->coup_sortie = $coup_sortie;

        return $this;
    }

    public function getCause(): ?string
    {
        return $this->cause;
    }

    public function setCause(string $cause): self
    {
        $this->cause = $cause;

        return $this;
    }
}

src/Form/SortieType.php
<?php

namespace App\Form;

use App\Entity\Sortie;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SortieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('coup', TextType::class,[
                "label" => "Numéro"
            ])
            ->add('date_sortie', DateType::class,[
                "widget" => "single_text",
                'attr' => [
                    "label" => "Date de sorte"
                ]
            ])
            ->add('coup_sortie', IntegerType::class, [
                "label" => "Montant"
            ])
            ->add('cause', TextType::class, [
                "label" => "Motif"
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Sortie::class,
        ]);
    }
}

src/Controller/SortieController.php
<?php

namespace App\Controller;

use App\Entity\Sortie;
use App\Form\SortieType;
use App\Repository\SortieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/sortie")
 */
class SortieController extends AbstractController
{
    /**
     * @Route("/", name="sortie_index", methods={"GET"})
     */
    public function index(SortieRepository $sortieRepository): Response
    {
        return $this->render('sortie/index.html.twig', [
            'sorties' => $sortieRepository->findAll(),
        ]);
    }

    /**
     * @Route("/nouvel-sortie", name="sortie_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $sortie = new Sortie();
        $form = $this->createForm(SortieType::class, $sortie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($sortie);
            $entityManager->flush();

            return $this->redirectToRoute('sortie_index');
        }

        return $this->render('sortie/new.html.twig', [
            'sortie' => $sortie,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="sortie_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Sortie $sortie): Response
    {
        $form = $this->createForm(SortieType::class, $sortie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('sortie_index');
        }

        return $this->render('sortie/edit.html.twig', [
            'sortie' => $sortie,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/delete", name="sortie_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Sortie $sortie): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($sortie);
        $entityManager->flush();

        return $this->redirectToRoute('sortie_index');
    }
}

templates/sortie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification du sorti{% endblock %}

{% block body %}
    {% include "type_materiel/form.html.twig" with {
        action_title: "Modification",
        entity_title: "sortie",
        btn_background: "success",
        button_label: "Modifier",
        path_list: path('sortie_index')
    } %}
{% endblock %}

templates/sortie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sortie {{ parent() }}{% endblock %}

{% block body %}
     <section class="container my-3">
     
        {% include "partials/new.with.access.html.twig" with {
            entity_title: "sorties",
			new_title: "sortie",
            path_new: path('sortie_new')
        } %}

		{% include "partials/notification.html.twig" %}

		<table class="table" id="table">
			<thead>
				<tr>
                    <td>Numero</td>
                    <td>Date de sortie</td>
                    <td>Montant</td>
                    <td>Motif</td>
                    {% include "partials/thead.action.html.twig" %}
				</tr>
			</thead>
			<tbody>
				{% for sortie in sorties %}
					<tr>
                        <td>{{ sortie.coup }}</td>
                        <td>{{ sortie.dateSortie ? sortie.dateSortie|date('d-m-Y') : '' }}</td>
                        <td>{{ sortie.coupSortie }}</td>
                        <td>{{ sortie.cause }}</td>
						<td>
							{% include "partials/action.html.twig" with {
								path_edit: path('sortie_edit', {'id': sortie.id}),
								path_delete: path('sortie_delete', {'id': sortie.id})
							} %}
						</td>
					</tr>
				{% else %}
					<tr align="center">
						<td colspan="3">Aucune sortie</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
    </section>
{% endblock %}

templates/sortie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau type de matériel{% endblock %}

{% block body %}
    {% include "type_materiel/form.html.twig" with {
        action_title: "Enregistrement",
        entity_title: "sortie",
        btn_background: "primary",
        button_label: "Enregistrer",
        path_list: path('sortie_index')
    } %}
{% endblock %}