src/Entity/DetailMateriel.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use App\Repository\DetailMaterielRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=DetailMaterielRepository::class)
 * @UniqueEntity(fields={"nom_materiel"},message="Ce détail matériel existe déjà")
 * @UniqueEntity(fields={"reference"},message="Ce reference existe déjà")
 */
class DetailMateriel
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("detail-materiel:read")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Materiel::class, inversedBy="detailMateriels")
     * @ORM\JoinColumn(nullable=true)
     * @Assert\NotBlank(message="Le nom du matériel est obligatoire")
     */
    private $materiel;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(message="Le nom du matériel est obligatoire")
     * @Assert\Length(max=100,maxMessage="La caractère du nom du matériel est au maximum 100 caractères")
     * @Groups("detail-materiel:read")
     */
    private $nom_materiel;

    /**
     * @ORM\Column(type="string", length=10)
     * @Assert\Length(max=10,maxMessage="La caractère du categorie est au maximum 10 caractères")
     * @Groups("detail-materiel:read")
     */
    private $categorie;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\NotBlank(message="La quantité est obligatoire")
     * @Assert\PositiveOrZero(message="La quantité minimal est 0")
     * @Groups("detail-materiel:read")
     */
    private $qte;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank(message="Le prix unitaire est obligatoire")
     * @Assert\PositiveOrZero(message="Le prix minimal est 0")
     * @Groups("detail-materiel:read")
     */
    private $prixUnitaire;

    /**
     * @ORM\ManyToOne(targetEntity=Departement::class, inversedBy="detailMateriels")
     * @ORM\JoinColumn(nullable=true)
     */
    private $departement;

    /**
     * @ORM\Column(type="datetime")
     * @Groups("detail-materiel:read")
     */
    private $dateApprovisionnement;

    /**
     * @ORM\ManyToMany(targetEntity=Achat::class, mappedBy="detailMateriel")
     */
    private $achats;

    /**
     * @ORM\Column(type="string", length=20)
     * @Assert\NotBlank(message="Le réference est obligatoire")
     * @Groups("detail-materiel:read")
     */
    private $reference;

    public function __construct()
    {
        $this->achats = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMateriel(): ?Materiel
    {
        return $this->materiel;
    }

    public function setMateriel(?Materiel $materiel): self
    {
        $this->materiel = $materiel;

        return $this;
    }

    public function getNomMateriel(): ?string
    {
        return $this->nom_materiel;
    }

    public function setNomMateriel(string $nom_materiel): self
    {
        $this->nom_materiel = $nom_materiel;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getQte(): ?int
    {
        return $this->qte;
    }

    public function setQte(int $qte): self
    {
        $this->qte = $qte;

        return $this;
    }

    public function getPrixUnitaire(): ?float
    {
        return $this->prixUnitaire;
    }

    public function setPrixUnitaire(float $prixUnitaire): self
    {
        $this->prixUnitaire = $prixUnitaire;

        return $this;
    }

    public function getDepartement(): ?Departement
    {
        return $this->departement;
    }

    public function setDepartement(?Departement $departement): self
    {
        $this->departement = $departement;

        return $this;
    }

    public function getDateApprovisionnement(): ?\DateTimeInterface
    {
        return $this->dateApprovisionnement;
    }

    public function setDateApprovisionnement(\DateTimeInterface $dateApprovisionnement): self
    {
        $this->dateApprovisionnement = $dateApprovisionnement;

        return $this;
    }

    /**
     * @return Collection|Achat[]
     */
    public function getAchats(): Collection
    {
        return $this->achats;
    }

    public function addAchat(Achat $achat): self
    {
        if (!$this->achats->contains($achat)) {
            $this->achats[] = $achat;
            $achat->addDetailMateriel($this);
        }

        return $this;
    }

    public function removeAchat(Achat $achat): self
    {
        if ($this->achats->removeElement($achat)) {
            $achat->removeDetailMateriel($this);
        }

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getTotalQty()
    {
        $qty_initial = $this->getQte() != 0 ? $this->getQte() : 0;
        $achats = $this->getAchats()->getValues();
        $qte_achete = [];
        $total_qte_achete = 0;

        if (count($achats) > 0){
            for ($i=0; $i < count($achats); $i++){
                array_push($qte_achete,$achats[$i]->getQteAchete());
            }
            $total_qte_achete = array_sum($qte_achete);
        }

        $qteTotal = $qty_initial - $total_qte_achete;

        return $qteTotal;
    }
}

src/Form/AbonneType.php
<?php

namespace App\Form;

use App\Entity\Achat;
use App\Entity\DetailMateriel;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AbonneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('dateEcheance',DateType::class,[
                "widget" => "single_text",
                'attr' => [
                    "class" => "echeance"
                ]
            ])
            ->add('qteAchete',IntegerType::class,[
                "label" => "Quantité",
                'attr' => [
                    "class" => "quantity"
                ]
            ])
            ->add('avance',IntegerType::class,[
                'attr' => [
                    "class" => "avance"
                ]
            ])
            ->add('detailMateriel',EntityType::class,[
                "class" => DetailMateriel::class,
                "choice_label" => "nom_materiel",
                "label" => "Détail matériel",
                "mapped" => false,
                'attr' => [
                    "class" => "materiel"
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Achat::class,
        ]);
    }
}

src/Controller/AbonneController.php
<?php

namespace App\Controller;

use App\Entity\Achat;
use App\Form\AbonneType;
use App\Repository\AchatRepository;
use App\Repository\DetailMaterielRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
* @Route("/abonne")
*/
class AbonneController extends AbstractController
{
    const TYPE_PAIEMENT = "Abonné";

    /**
     * @Route("/", name="abonne_index")
     */
    public function abonne(AchatRepository $achatRepository): Response
    {
        return $this->render('abonne/index.html.twig', [
            'abonnes' => $achatRepository->getAllAbonne()
        ]);
    }

    /**
     * @Route("/{code_facture}/nouveau-abonnement/", name="abonne_new", methods={"GET","POST"})
     */
    public function abonnement(Request $request,AchatRepository $achatRepository,DetailMaterielRepository $detailmaterielRepository,$code_facture): Response
    {
        $nomAbonnes = $achatRepository->nomAcheteur();

        $achat = new Achat();

        $form  = $this->createForm(AbonneType::class, $achat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data           = $request->request->all();
            $codeFacture    = $data["abonne"]["codeFacture"];
            $nomAcheteur    = $data['abonne_nomAcheteur'];
            $dateAchat      = new \DateTime();
            $dateEcheance   = new \DateTime($data["abonne"]["dateEcheance"]);
            $detailMateriel = $data["abonne"]["detailMateriel"];

            if (isset($data["abonne"]["detailMateriel"])) {
                foreach ($data["abonne"]["detailMateriel"] as $key => $materiel_id) {
                    $detailmateriel = $detailmaterielRepository->find($materiel_id);
                    $achat->addDetailMateriel($detailmateriel);

                    if (isset($data["qteAchete"][$key])) {
                        $achat->setQteAchete($data["qteAchete"][$key]);
                    }

                    if (isset($data["avance"][$key])) {
                        $achat->setAvance($data["avance"][$key]);
                    }

                    $achat->setCodeFacture($codeFacture);
                    $achat->setNomAcheteur($nomAcheteur);
                    $achat->setDateAchat($dateAchat);
                    $achat->setDateEcheance($dateEcheance);
                    $achat->setTypePaiement(self::TYPE_PAIEMENT);

                    $entityManager = $this->getDoctrine()->getManager();
        
                    $entityManager->persist($achat);
                    $this->addFlash('success','Abonné ajouté avec succès');
                    $entityManager->flush();
        
                    return $this->redirectToRoute('abonne_index');
                }
            }

        }

        return $this->render('abonne/new.html.twig', [
            'form' => $form->createView(),
            'nom_abonnes' => $nomAbonnes,
            'detail_abonnes' => $achatRepository->findBy(["codeFacture" => $code_facture])
        ]);
    }

    /**
     * @Route("/nouveau/abonnement/", name="abonnes_new", methods={"GET","POST"})
     */
    public function nouveauAbonnement(Request $request,EntityManagerInterface $manager,
                                        DetailMaterielRepository $detailmaterielRepository)
    {
        $data = $request->request->all();
        if (isset($data["materiel_id"])) {
            foreach ($data["materiel_id"] as $key => $materiel_id) {
                $achat = new Achat();
                $detailmateriel = $detailmaterielRepository->find($materiel_id);
                $achat->addDetailMateriel($detailmateriel);

                if (isset($data["quantity"][$key])) {
                    $achat->setQteAchete((int) $data["quantity"][$key]);
                }

                if (isset($data["avance"][$key])) {
                    $achat->setAvance((int) $data["avance"][$key]);
                }

                if (isset($data["nom_acheteur"][$key])) {
                    $achat->setNomAcheteur($data["nom_acheteur"][$key]);
                }

                if (isset($data["code_facture"][$key])) {
                    $achat->setCodeFacture($data["code_facture"][$key]);
                }

                if (isset($data["date_echeance"][$key])) {
                    $dateEcheance = new \Datetime($data["date_echeance"][$key]);
                    $achat->setDateEcheance($dateEcheance);
                }

                $dateAchat = new \Datetime();
                $tempsAchat = $dateAchat->format('h:i:s');
                $achat->setDateAchat($dateAchat);
                $achat->setTempsAchat($tempsAchat);

                $achat->setTypePaiement(self::TYPE_PAIEMENT);

                $manager->persist($achat);
                $manager->flush();
            }
        }

        return $this->json(["success" => true,"message" => "Abonné ajouté avec succès"]);
    }

    /**
    * @Route("/{code_facture}/detail", name="abonne_show")
    */
    public function show(AchatRepository $achatRepository,$code_facture)
    {
        return $this->render('abonne/show.html.twig', [
            'detail_abonnes' => $achatRepository->findBy(["codeFacture" => $code_facture])
        ]);
    }

    /**
     * @Route("/{code_facture}/delete", name="abonne_delete", methods={"DELETE"})
    */
    public function delete(AchatRepository $achatRepository,$code_facture)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $abonnesByCode = $achatRepository->findBy(["codeFacture" => $code_facture]);
        $abonnes = [];

        for ($i=0; $i < count($abonnesByCode); $i++) { 
            $abonne_id = $abonnesByCode[$i]->getId();
            array_push($abonnes,$achatRepository->find($abonne_id));
        }

        foreach ($abonnes as $abonne) {
            $entityManager->remove($abonne);
            $entityManager->flush();
        }
        
        $this->addFlash('success','Abonné supprimé avec succès');

        return $this->redirectToRoute('abonne_index');
    }
}

templates/abonne/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Liste des abonnés {{ parent() }} {% endblock %}
	
{% block body %}
	<section class="container my-5">
        <h3 class="text-center">Liste des abonnés</h3>
		{% include "partials/notification.html.twig" %}
		<div class="notification-add-abonne"></div>
		<table class="table" id="table">
			<thead>
				<tr>
					<th>Code facture</th>
					<th>Nom l'acheteur</th>
					{% include "partials/thead.action.html.twig" %}
				</tr>
			</thead>
			<tbody>
				{% for abonne in abonnes %}
					<tr>
						<td>FAC{{ abonne.code_facture | upper }}</td>
						<td>{{ abonne.nom_acheteur }}</td>
						<td>
							{% if is_granted("ROLE_RESPONSABLE") %}
								<a class="btn btn-sm btn-primary px-4 btn_rounded" href="{{ path('abonne_new', {'code_facture': abonne.code_facture}) }}">
									Nouvel abonnement
								</a>
								<a class="btn btn-sm btn-secondary px-4 btn_rounded" href="{{ path('abonne_show', {'code_facture': abonne.code_facture}) }}">
									Voir
								</a>
								<form method="post" action="{{ path('abonne_delete', {'code_facture': abonne.code_facture}) }}" class="d-inline-block" onsubmit="return confirm('Vous voulez vraiment supprimer');">
									<input type="hidden" name="_method" value="DELETE">
									<button class="btn btn-sm btn-danger px-4 btn_rounded" role="button">Supprimer</button>
								</form>
							{% endif %}
						</td>
					</tr>
				{% else %}
					<tr align="center">
						<td colspan="11">Aucun liste d'abonné</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</section>
{% endblock %}

templates/abonne/new.html.twig
{% extends 'base.html.twig' %}
{% block title %}Nouvel abonnement{% endblock %}
{% block body %}
    <div class="container">
        <h4 class="text-center mt-2">Enregistrement d'un nouvel abonnement</h4>
            <div class="col-sm-4 notify-add-abonne">
                {{ form_start(form) }}
                    {{ form_row(form.dateEcheance) }}
                    <hr class="bg-success" />
                    <div class="form-abonne">
                        <div class="form-abonne-item" data-key="0">
                            <div class="form-group d-none">
                                <label for="abonne_nomAcheteur" class="required">Nom de l'abonné</label>
                                <input type="text" id="abonne_nomAcheteur" name="abonne[nomAcheteur]" 
                                       required="required" class="form-control nom-acheteur" value= {{ detail_abonnes[0].nomAcheteur }}>
                            </div>
                            <div class="form-group d-none">
                                <label for="abonne_codeFacture" class="required">Code facture</label>
                                <input type="text" id="abonne_codeFacture" name="abonne[codeFacture]" 
                                       required="required" class="form-control code-facture" value= {{ detail_abonnes[0].codeFacture }}>
                            </div>
                            <div class="form-group d-none">
                                <label for="abonne_dateEcheance" class="required">Date echeance</label>
                                <input type="text" id="abonne_dateEcheance" name="abonne[dateEcheance]" required="required" class="form-control date-echeance">
                            </div>
                            {{ form_row(form.qteAchete) }}
                            <span class='error-quantity' style='color:red;'>La quantité est au minimum 0</span>
                            {{ form_row(form.avance) }}
                            <span class='error-avance' style='color:red;'>L'avance est au minimum 0</span>
                            {{ form_row(form.detailMateriel) }}
                            <button class="btn btn-sm btn-danger px-4 btn_rounded btn-remove-abonne mb-2 d-none" type="button">Supprimer cet abonnement</button>
                            <hr class="bg-success" />
                        </div>
                    </div>
                    <div class="mb-3">
                        <button class="btn btn-sm btn-success px-4 btn_rounded btn-save-more-abonne mb-2" data-key="0" type="button">Plus d'abonnement</button>
                        <div>
                            <button class="btn btn-sm btn-primary btn-save-abonne px-4 btn_rounded ">Enregistrer</button>
                            <a href="{{ path('abonne_index') }}" class="btn btn-sm btn-warning px-4 btn_rounded">Retourner</a>
                        </div>
                    </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script>
        var url_add_abonne = "{{ path('abonnes_new') }}";
        var absolute_url_abonne = "{{ url('abonne_index') }}";
    </script>
    <script src="{{ asset('js/abonne.js') }}"></script>
{% endblock %}

templates/abonne/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Détail de l'abonnement {{ parent() }}
{% endblock %}

{% block body %}
	<section class="container my-5">
		<h3 class="text-center mb-5">Détail de l'abonnement</h3>
		<div class="d-block">
			<b>Code du facture :</b>
			FAC{{ detail_abonnes[0].codeFacture | upper }}<br><br>
			<b>Nom de l'acheteur :</b>
			{{ detail_abonnes[0].nomAcheteur }}
		</div>
        <div class="container">
            <div class="row">
		    {% for detail_abonne in detail_abonnes %}
                <div class="col-sm-4">
                    <div class="card shadow mt-5">
                            <div class="card-header bg-info text-center text-white">
                                {% for detailMateriel in detail_abonne.detailMateriel %}
                                    {{ detailMateriel.nomMateriel }}
                                {% endfor %}
                            </div>
                            <div class="card-body">
                                {% set qteAchete = detail_abonne.qteAchete %}
                                <div>
                                    <div class="py-2">
                                        <b>Quantité acheté :</b>
                                        {{ qteAchete }}
                                    </div>
                                    <div class="py-2">
                                        <b>Prix unitaire :</b>
                                        {% for detailMateriel in detail_abonne.detailMateriel %}
                                            {{ detailMateriel.prixUnitaire | number_format(0,'',' ') }}
                                            Fmg
                                        {% endfor %}
                                    </div>
                                    <div class="py-2">
                                        <b>Sous-total :</b>
                                        {% set subTotal = 0 %}
                                        {% for detailMateriel in detail_abonne.detailMateriel %}
                                            {% set subTotal = subTotal + (detailMateriel.prixUnitaire * qteAchete) %}
                                            {{ subTotal | number_format(0,'',' ') }}
                                            Fmg
                                        {% endfor %}
                                    </div>
                                    <div class="py-2">
                                        {% set avance = detail_abonne.avance %}
                                        <b>Avance :</b>
                                        {{ avance | number_format(0,'',' ') }}
                                        Fmg
                                    </div>
                                    <div class="py-2">
                                        <b>Reste :</b>
                                        {{ (subTotal - avance) | number_format(0,'',' ') }}
                                        Fmg
                                    </div>
                                    <div class="py-2">
                                        <b>Date d'echeance :</b>
                                        {{ detail_abonne.dateEcheance | date("d/m/Y")}}
                                    </div>
                                    <div class="py-2">
                                        <b>Département :</b>
                                        {% for detailMateriel in detail_abonne.detailMateriel %}
                                            {{ detailMateriel.departement.nomDepartement }}
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                    </div>
                </div>
		    {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}